language: node_js

node_js:
  - "4.0"
  - "4"
  - "5"

env:
  - CXX=g++-4.8

before_install:
    - sudo add-apt-repository -y ppa:rethinkdb/ppa && sudo apt-get -y update && sudo apt-get install -y rethinkdb

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
