language: node_js

node_js:
  - "4.0"
  - "4"
  - "5"

env:
  - CXX=g++-4.8

before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y
  
before_script:
  - sudo rethinkdb --io-threads 2048 --daemon
  - ulimit -S -n 2048
  - sleep 10

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
